Add --print-path option and README updates
svenssonaxel/pdf-sign pull request #8
Opened 2024-03-21 17:54 UTC by brunetton

Thank you for this great software, I was looking for a tool like this one since some weeks ago.

I used it today and I missed some details to understand how it works. So I updated README and added a command line option to print signatures folder.

Hope this looks okay to you. Tell me !

Thanks again !

2024-03-22 05:13 UTC, svenssonaxel requested changes
Glad that you like the tool.
I think this is an improvement, but I think we should improve it some more before merging. You're very welcome to address these comments, but if you don't want to, I'll eventually get around to doing it myself. In the meantime, thank you!

2024-03-22 05:13 UTC, svenssonaxel commented on README.md
> +./pdf-sign "" --print-path
I wish the empty `""` wasn't needed.

2024-03-22 05:13 UTC, svenssonaxel commented on README.md
> +Now you'll have to put your signature in a PDF file in this folder, you can use `empty-3inx2in.pdf` empty PDF template for example.
Good, but the instruction under `## How` also needs correcting.

2024-03-22 05:13 UTC, svenssonaxel commented on README.md
> +
For clarity, perhaps add a line such as `Thereafter, you can begin using pdf-sign. For example:`
Otherwise the below code block could appear like it was about creating signatures.

2024-03-22 05:13 UTC, svenssonaxel commented on pdf-sign
> +        print(getSignatureDir())
This will print the correct path in almost all cases. The exception is when
* The user prefers to put the signatures under `~/.config` in order not to litter the home directory.
* `~/.config/pdf_signatures` does not exist (yet)
* `$PDF_SIGNATURE_DIR` and `XDG_CONFIG_HOME` are both unset.

In this situation, `pdf-sign "" --print-path` will print `/home/user/.pdf_signatures` even though it should have printed `/home/user/.config/pdf_signatures`.
I'm not exactly sure how to fix this, but I think it's a shame to make this improvement without going all the way.

2024-03-22 05:13 UTC, svenssonaxel commented on pdf-sign
> +parser.add_argument('-S', '--print-path', help='Print signatures path.', action='store_true')
Perhaps `-S` and `-s` are confusingly similar?

2024-03-26 16:00 UTC, brunetton commented on README.md
> +./pdf-sign "" --print-path
I wish too, it's quite ugly ! I'm not an argparse expert but I havn't succeed achieving it using argparse.

Anyway, after reconsideration I'd remove this option, as there is an error message that prints the signatures dir if it doesn't exists. In the README we could write something like:

> To know the signature directory to create, run `./pdf-sign my_pdf.pdf` and see the error message

What would you think about this ?

2024-03-26 16:06 UTC, brunetton commented on README.md
> +Now you'll have to put your signature in a PDF file in this folder, you can use `empty-3inx2in.pdf` empty PDF template for example.
Oh yes indeed. I'll merge both sections if you are okay

2024-03-26 16:15 UTC, brunetton commented on pdf-sign
> +        print(getSignatureDir())
Indeed. 

But this is out of the scope of this PR, as this is not a problem introduced by this PR, it was already the case before

Anyway, I'll finally suggest to turn back and forget adding this option.

2024-06-03 08:43 UTC, svenssonaxel commented
@brunetton I came up with a different solution that requires no extra options. Essentially, the help text and error messages are customized to explain the situation on your particular system. Check my branch `dev` and let me know wha you think.

2024-07-16 21:15 UTC, svenssonaxel commented
@brunetton PR rejected since the solution I mentioned above is now merged. Feel free to open an issue if you are not satisfied.

2024-07-16 21:15 UTC, closed without merging